
name: Test

on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/test.yml'
      - 'index.js'
      - 'conf/*'
      - 'hooks/*'



concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  testsshfs:
    if: ${{ !contains(github.repository, 'solaris') && !contains(github.repository, 'dragonflybsd')}}
    strategy:
      matrix:
        release: [ "12.4", "13.2", "14.0", ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: sshfs FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@1139483cbfb21dd1fb7f72ac9d127c8276f53988
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          pkg install -y curl
        mem: 2048
        copyback: false
        release: ${{ matrix.release }}
        nat: |
          "10022": "22"
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        sync: sshfs
        run: |
          tree .
          tree $HOME/work/
    - name: Test NAT
      run: 
        ssh -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"

  test:
    strategy:
      matrix:
        release: [ "12.4", "13.2", "14.0", ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@1139483cbfb21dd1fb7f72ac9d127c8276f53988
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          pkg install -y curl
        mem: 2048
        copyback: false
        release: ${{ matrix.release }}
        nat: |
          "10022": "22"
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
    - name: Test NAT
      run: 
        ssh -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"










