
name: Test

on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/test.yml'
      - 'index.js'
      - 'conf/*'
      - 'hooks/*'



concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  testsshfs:
    if: ${{ !contains(github.repository, 'solaris') && !contains(github.repository, 'dragonflybsd') && !contains(github.repository, 'omnios')}}
    strategy:
      matrix:
        release: [ "13.2", "14.0", ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: sshfs FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
      DEBUG: 1
    steps:
    - uses: actions/checkout@v4
    - name: Creating Web console
      uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8000
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@61bf2e1239e3db9c06b3e6440017e66fc6f5124f
      with:
        envs: 'DEBUG MYTOKEN MYTOKEN2'
        prepare: |
          pkg install -y curl
        mem: 2048
        release: ${{ matrix.release }}
        nat: |
          "10022": "22"
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        sync: sshfs
        run: |
          ls -lah /root/work
          tree $HOME/work/
          if [ -z "$(ls -A $HOME/work)" ]; then
            echo "sshfs error."
            exit 1
          fi
    - name: Test NAT
      run: 
        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"

  test:
    strategy:
      matrix:
        release: [ "13.2", "14.0", ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@61bf2e1239e3db9c06b3e6440017e66fc6f5124f
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          pkg install -y curl
        mem: 2048
        release: ${{ matrix.release }}
        nat: |
          "10022": "22"
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
    - name: Test NAT
      run: 
        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"










